### ISSUE TITLE
Question: Using SwiftCoAP with DTLS?

### ISSUE THREAD

**Issue by Mallenow** [stuffrabbit/SwiftCoAP#13]
Hello,

Is it possible to use SwiftCoap with DTLS? Unfortunately, I could not find anything about it.

Thanks for your help!
Mallenow

**Comment by stuffrabbit** [comment]
Hi Mallenow, 
SwiftCoAP doesn't provide DTLS by default. However, it should be possible to implement it as custom `SCCoAPTransportLayerProtocol` to be used as part of this library.

Feel free to contribute!

Thank you
