### ISSUE TITLE
Update to Swift 4/5 and Xcode 11?

### ISSUE THREAD

**Issue by danieleftodi** [stuffrabbit/SwiftCoAP#15]
Hi @stuffrabbit,

Would it be possible to update this code to Swift 4/5 and Xcode 11?

And maybe add the latest things from the C-lib implementation of CoAP? :) 

Cheers.

**Comment by stuffrabbit** [comment]
Hi, I will try to do the Swift update soon. Thanks for the reminder. 
Unfortunately, I am not up to date with the latest CoAP features. What exactly is missing?
Of course, please feel free to contribute to this repository :)

**Comment by danieleftodi** [comment]
@stuffrabbit 

Sure. Let's do it :-) 

Regarding new features, I don't know exactly what has changed, but it makes sense to make sure we are reflecting all of the implementation in https://github.com/obgm/libcoap  (the C-library) and the [CoAP spec](http://coap.technology/spec.html)

Also, from my quick look ... it would make sense to make this a "[Swift Package](https://developer.apple.com/documentation/xcode/creating_a_swift_package_with_xcode)" ... to make it easier for others to add it to their code 😊

**Comment by danieleftodi** [comment]
Hi, @stuffrabbit,

I updated the code to Swift 4.2 and created a [pull request](https://github.com/stuffrabbit/SwiftCoAP/pull/16) 👍🏻

I have also added an Xcode Workspace to the project. This will make it easier to work, and add other Targets too.

I'm planing on making:
1) Convert this code into a proper Swift Package (to make it easier for everyone to add it to their projects...)
2) macOS Command Line version
3) a Vapor Server Side Swift
