### ISSUE TITLE
Execute request from Lwm2m server

### ISSUE THREAD

**Issue by mlindstedt** [stuffrabbit/SwiftCoAP#3]
Hi,

I am wondering how to use SwiftCoap protocol, when I want to make a higher layer call?

Let's assume I implement an LWM2M server in an iOS app. The LWM2M server will be setup together with your nice SwiftCoAP implementation, which I setup as CoAP server. The LWM2M operations "register" and "unregister" operations that a LWM2M client can send to my LWM2M server are clear how to handle, since they are incoming requests to the server.

But outgoing requests, like LWM2M operation "execute" which the LWM2M server shall send to a LWM2M client, how do you suggest that I shall use SwiftCoAP to do that? Shall the LWM2M server suddenly setup your code as a CoAP client to do that, whilst in normal case for incoming requests, where it is a CoAP server?

**Comment by stuffrabbit** [comment]
Hi mlindstedt,
thank your for using SwiftCoAP. According to your scenario I think that using both the client as well as the server implementation of SwiftCoAP would be the most suitable solution. Executing an initial request can only be performed by the client. Hope this is of any help.

**Comment by mlindstedt** [comment]
Yes, the answer is of help. thanks for the quick reply.
