### ISSUE TITLE
Many compiler warnings for Swift3

### ISSUE THREAD

**Issue by mlindstedt** [stuffrabbit/SwiftCoAP#4]
Hi Stuffrabbit,

I like your CoAP implementation of Swift.

But when using XCode 7.3 it seems to already have support for Swift3, i.e next version after Swift2.2. Thus when using SCClient, SCServer or SCMessage about 20 compiler warnings appear, for example:
- SCClient.swift:208:129: Use of string literal for Objective-C selectors is deprecated; use '#selector' instead
- SCClient.swift:205:34: '++' is deprecated: it will be removed in Swift 3
- SCMessage.swift:574:67: 'init(start:end:)' is deprecated: it will be removed in Swift 3.  Use the '..<' operator.
- 'sendAsynchronousRequest(_:queue:completionHandler:)' was deprecated in iOS 9.0: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h

Will you make an update of SwiftCoAP to fix those compiler warnings?

See here for more details about Swift 3:
https://github.com/apple/swift-evolution
https://swift.org/blog/swift-3-api-design/

**Comment by stuffrabbit** [comment]
Hey, yes I am aware of this. I will provide an update, as soon as I'll find the time :)

**Comment by mlindstedt** [comment]
Ok, I've tested to fix the warnings by myself and the compiler had suggestions for most of them, the other ones I solved manually. So I will close this question.
