### ISSUE TITLE
SwiftCoAP + LWM2M?

### ISSUE THREAD

**Issue by mlindstedt** [stuffrabbit/SwiftCoAP#5]
Hi Stuffrabbit,

I like your CoAP implementation of Swift and it seems to work fine when trying out your CoAP server implementation together with this CoAP client in the Firefox webbrowser:
https://addons.mozilla.org/en-US/firefox/addon/oma-lwm2m-devkit/

Now my questioN:
1) Have you made any integrations with LWM2M with your CoAP library?

LWM2M implementations:
https://github.com/eclipse/wakaama (Implemented in C)
https://github.com/FlowM2M/AwaLWM2M (Implemented in C)
https://github.com/eclipse/leshan (Implemented in Java)
according to:
https://en.wikipedia.org/wiki/OMA_LWM2M

Maybe you've built wakamaa as a iOS-library (so its still C code), but with integration to SwiftCoAP?

2) and/or maybe you have started to port some parts of Wakamaa or Leshan to Swift? I.e some of the client or server LWM2M-parts?

**Comment by mlindstedt** [comment]
Hi Stuffrabbit,

you had very quick answers on my other 2 questions, do you have an answer on this question too?

**Comment by stuffrabbit** [comment]
Hey mlindstedt,
sorry for the late answer. To be short: No have not implemented any LWM2M integrations till now. Maybe you can start a fork? :)

**Comment by mlindstedt** [comment]
Hi stuffrabbit,

I actually started on a LWM2M integration, for REGISTER / DEREGISTER and they worked fine. However when I implemented READ, then I ran into severe problems in SwiftCoap-code and I was doing lot of debugging in your code to try to find problem, the bits and bytes on Coap-level doesn't seem to be sent correctly. After several days of debugging, and not being able to make it work, I unfortunately had to abandon, and instead decided to go with Wakamaa implementation:

https://github.com/eclipse/wakaama

Even though Wakamaa is written in C, I managed to integrate the library into my Swift app.

Afterwards it has come to my attention that Firefox web browser:
https://addons.mozilla.org/en-US/firefox/addon/oma-lwm2m-devkit/
used PUT and not POST for LWM2M READ and that might be the reason why it didn't work..

**Comment by stuffrabbit** [comment]
Hi mlindstedt,
good to hear that you were able to find a solution for your problem. So you mean that there is a bug inside the CoAP-message parsing of SwiftCoAP? Or what were these severe problems about?

**Comment by mlindstedt** [comment]
It seems to me that there is a bug, but I only put in 4 debug working days, before I gave up. Like I said, when I implemented LWM2M register and deregister on top of SwiftCoap in my iOS app, then SwiftCoap worked fine, but when I implemented LWM2M read or execute, then SwiftCoap didn't make other side trigger on what it sent, so either the problem was in SwiftCoap or in the other end (LWM2M client).

In my case I used Firefox web browser with a plugin, to use it as LWM2M client, whilst the iOS app with SwiftCoap was LWM2M server.

However, later on it turned out, that Firefox plugin was not correctly implemented, it followed old LWM2M standard which made it use PUT and not POST for LWM2M read, which might be reason why it didn't work.

But, I also tried Wakamaa as LWM2M client towards my iOS app and it had same problem, so my suggestion is that you try to implement some parts of the upper layer, i.e LWM2M on top of SwiftCoap, to see if you can make it work. REGISTER and READ should be enough for you to see if you can get same problem.
