### ISSUE TITLE
Objective-C interface support

### ISSUE THREAD

**Issue by daveismith** [stuffrabbit/SwiftCoAP#6]
I'm trying to try out SwiftCoAP with Objective-C. Are there any examples of how to send requests / act as a server bridged from Objective-C.

**Comment by stuffrabbit** [comment]
Hey daveismith. Unfortunately, I cannot provide an example in Objective-C at the moment. Do you have problems using the library in an Objective-C environment?

**Comment by daveismith** [comment]
I couldn't actually figure out how to instantiate an SCMessage and set the
code, etc.

David

**Comment by stuffrabbit** [comment]
Do you have any updates on this? Maybe you could try the iCoAP library for now.

**Comment by daveismith** [comment]
Unfortunately for the IoT standard I'm working on I need to have both a client and server running. I'll figure out swift eventually. I haven't had opportunity to loop back to this as I've been too busy with other parts of the project.
