### ISSUE TITLE
iOS 10 breaks the App

### ISSUE THREAD

**Issue by wiresio** [stuffrabbit/SwiftCoAP#7]
Unfortunately this great App doesn't work with iOS 10.1 anymore. Would be great (again ;-) if this issue can be fixed.

**Comment by stuffrabbit** [comment]
Hey, do you mean the library itself or the small demo app? In fact i did not update for Siwft3/iOS 10 yet.

**Comment by wiresio** [comment]
Thanks for the quick reply! I'm refering to the App downloaded from the App Store and running on iPad w/ iOS 10.1.

**Comment by stuffrabbit** [comment]
Hey, 
so you mean "myCoAP"?  What is the exact problem? Does the app crash? And yes, when exactly? Did you try a fresh installation?
For me, myCoAP does work for iOS 10.1 on iPhone/iPad.
Thanks for the Feedback :)

**Comment by wiresio** [comment]
Yes "myCoap". CoAP resource discovery does not deliver results such can I cannot access the CoAP server. Will try uninstalling and re-installing (does that really help?).

**Comment by stuffrabbit** [comment]
Hmm, maybe this might help :) did you try to access other servers (e.g. "coap.me:5683)?

**Comment by wiresio** [comment]
Thanks & please close here - was my fault due to a misconfigured CoAP server.

**Comment by stuffrabbit** [comment]
Alright :)
